/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TercerRepositorio;

import javax.swing.JOptionPane;

/**
 *
 * @author liborio
 */
public class EjercicioTres extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioTres
     */
    public EjercicioTres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMAhorrado = new javax.swing.JTextField();
        txtSTotal = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Banco");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 80, 20));

        jLabel2.setText("Monto Ahorrado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setText("Saldo Total");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        txtMAhorrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMAhorradoKeyTyped(evt);
            }
        });
        jPanel1.add(txtMAhorrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, -1));
        jPanel1.add(txtSTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 70, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdCalcularKeyTyped(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdBorrarKeyTyped(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMAhorradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMAhorradoKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMAhorradoKeyTyped

    private void cmdCalcularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdCalcularKeyTyped

        double SFinal, SInicial, Oper;


        if (txtMAhorrado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por Favor Digite Su Monto Ahorrado", "Error", JOptionPane.ERROR_MESSAGE);
            txtMAhorrado.requestFocusInWindow();
        } else {
            SInicial = Double.parseDouble(txtMAhorrado.getText());

            if (SInicial == 0) {
                JOptionPane.showMessageDialog(this, "Su Saldo No Puede Ser 0", "Error", JOptionPane.ERROR_MESSAGE);
                txtMAhorrado.requestFocusInWindow();
                txtMAhorrado.selectAll();;
            }
            SFinal = SInicial * 0.15;
            Oper = SInicial - SFinal;
            txtSTotal.setText(String.valueOf(Oper));

        }
                txtSTotal.setText("");
    }//GEN-LAST:event_cmdCalcularKeyTyped

    private void cmdBorrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdBorrarKeyTyped

        txtMAhorrado.setText("");
        txtSTotal.setText("");
        txtMAhorrado.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioTres().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMAhorrado;
    private javax.swing.JTextField txtSTotal;
    // End of variables declaration//GEN-END:variables
}
